version: '3.8'
services:
  mlflow:
    image: mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://your-bucket/mlflow/